### PR TITLE
Pr.ffmpeg.new

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by headupinclouds** [comment]
Okay, yes, it is better to separate them.  Thanks.

**Review by headupinclouds — APPROVED** [review]

**Comment by headupinclouds** [comment]
Shall I merge + tag?

**Comment by ruslo** [comment]
It's not working.

To enable the feature we need `HAVE_FFMPEG`:
- https://github.com/hunter-packages/opencv/blob/v4.0.0-p1/modules/videoio/CMakeLists.txt#L143-L155

If you will add `set(HAVE_FFMPEG TRUE)` this test will run:
- https://github.com/hunter-packages/opencv/blob/v4.0.0-p1/cmake/OpenCVFindLibsVideo.cmake#L235-L253

For `try_compile` the variable `FFMPEG_LIBRARIES` should not be an imported target but list of full paths instead:
```cmake
        get_target_property(
          imported_configurations
          ffmpeg::${lib}
          IMPORTED_CONFIGURATIONS
          )
        list(GET imported_configurations 0 imported_configuration)
        get_target_property(
          imported_location
          ffmpeg::${lib}
          IMPORTED_LOCATION_${imported_configuration}
          )
        list(APPEND FFMPEG_INCLUDE_DIRS "${${lib}_INCLUDE_DIR}")
        list(APPEND FFMPEG_LIBRARIES ${imported_location})
```

If uncomment this and run the test:
- https://github.com/hunter-packages/opencv/blob/v4.0.0-p1/cmake/OpenCVFindLibsVideo.cmake#L247

Result will be:
```
fatal error: libswscale/swscale.h: No such file or directory
```

Headers from this directory are not installed:
- https://github.com/hunter-packages/FFmpeg/blob/n4.1-dev-45499e557c-p3/CMakeLists.txt#L604-L613

Configuration I've used for testing (not in `master` yet):
- https://github.com/ruslo/hunter/commit/3c42feb474f319437ab0767ee0bfb2ece1996ccb

**Comment by headupinclouds** [comment]
Thanks for the snippet.  I'll work on fixes, starting with the ffmpeg.  I'm assuming libswscale headers should be added to the installation.  I'll also make a runtime test using `cv::VideoCapture` to test that input fails with `WITH_FFMPEG=OFF` and works with `WITH_FFMPEG=ON`.

**Comment by headupinclouds** [comment]
After incorporating your pointers, I was able to fix the integration in [this commit](https://github.com/headupinclouds/opencv/commit/cdf509fb9f61a346f21c2259a30b9288c3f3c92c), but I realized the minimal CMake FFMPEG port wasn't quite sufficient for my needs, and a custom autotool based scheme was more appropriate to support FFMPEG builds with x264 support.  I'll follow up with FFMPEG related discussion in the Hunter fork, since it could impact OpenCV usage.

**Pull request merged**
