### PR TITLE
Hunter 3.3.1

### PR DESCRIPTION
**Pull request by xsacha**
Needs new branch

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
Conflicts

**Comment by xsacha** [comment]
Conflicts with what? The target branch doesn't exist yet.

By the way, welcome back from holiday!

**Comment by ruslo** [comment]
> Needs new branch

> The target branch doesn't exist yet

Missed that, sorry :)

**Review by ruslo — APPROVED** [review]

**Comment by ruslo** [comment]
Released: https://github.com/hunter-packages/opencv/releases/tag/v3.3.1-p0

**Pull request merged**
